{% set name = "sqlakeyset" %}
{% set version = "2.0.1787969905" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/sqlakeyset-{{ version }}.tar.gz
  sha256: aade1e9cd75d47d01ee486b327d83b59b16e78443aa432189d34185e347d7ed4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
  run:
    - packaging >=20.0
    - python >={{ python_min }}
    - python-dateutil
    - sqlalchemy >=1.3.11
    - typing_extensions >=4,<5

test:
  imports:
    - sqlakeyset
    - sqlakeyset.serial
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/djrobstep/sqlakeyset
  summary: offset-free paging for sqlalchemy
  license: Unlicense
  license_file: LICENSE

extra:
  recipe-maintainers:
    - acarapetis
