{% set name = "sqlakeyset" %}
{% set version = "2.0.1691149549" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqlakeyset-{{ version }}.tar.gz
  sha256: 935f2818c6f4ce70b249b17ed6eb797af9df32b24ed7ddba377177fd237fcb83

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7,<4.0
    - poetry ~=1.3.0
  run:
    - packaging >=20.0
    - python >=3.7
    - python-dateutil
    - sqlalchemy >=1.3.11
    - typing_extensions >=4,<5

test:
  imports:
    - sqlakeyset
    - sqlakeyset.serial
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/djrobstep/sqlakeyset
  summary: offset-free paging for sqlalchemy
  license: Unlicense
  license_file: LICENSE

extra:
  recipe-maintainers:
    - acarapetis
