{% set name = "sqlakeyset" %}
{% set version = "1.0.1655946639" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqlakeyset-{{ version }}.tar.gz
  sha256: 04224c6e8cea317cb7e70223e818570c731b1ac3f1a379c37d80353644b42e4a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - packaging >=20.0
    - python >=3.4
    - python-dateutil
    - sqlalchemy >=1.3.11

test:
  imports:
    - sqlakeyset
    - sqlakeyset.serial
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/djrobstep/sqlakeyset
  summary: offset-free paging for sqlalchemy
  license: Unlicense
  license_file: LICENSE

extra:
  recipe-maintainers:
    - acarapetis
