{% set name = "sqlakeyset" %}
{% set version = "2.0.1733540710" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sqlakeyset-{{ version }}.tar.gz
  sha256: 1dc43df81cac6b992acde5605d7182d7f1f6bf9d97bbfd7ecc0272459557940a

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
  run:
    - packaging >=20.0
    - python >={{ python_min }}
    - python-dateutil
    - sqlalchemy >=1.3.11
    - typing_extensions >=4,<5

test:
  imports:
    - sqlakeyset
    - sqlakeyset.serial
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/djrobstep/sqlakeyset
  summary: offset-free paging for sqlalchemy
  license: Unlicense
  license_file: LICENSE

extra:
  recipe-maintainers:
    - acarapetis
