{% set name = "sqlakeyset" %}
{% set version = "1.0.1679485999" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqlakeyset-{{ version }}.tar.gz
  sha256: 478a662eb4b4092cc5fa6bbbfabdb856783b760690af2dd8341987d60ba9d924

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - poetry ~=1.3.0
  run:
    - packaging >=20.0
    - python >=3.7
    - python-dateutil
    - sqlalchemy >=1.3.11

test:
  imports:
    - sqlakeyset
    - sqlakeyset.serial
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/djrobstep/sqlakeyset
  summary: offset-free paging for sqlalchemy
  license: Unlicense
  license_file: LICENSE

extra:
  recipe-maintainers:
    - acarapetis
